name: Build Zed for Windows

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Enable Long Paths
      run: |
        reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f
        Start-Sleep -Seconds 5
      shell: pwsh

    - name: Set Cargo Home and Target Directory
      run: |
        echo "CARGO_HOME=C:\cargo" >> $GITHUB_ENV
        echo "CARGO_TARGET_DIR=C:\cargo_target" >> $GITHUB_ENV

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Install Toolchain
      run: rustup target add wasm32-wasi

    - name: Clone Source Code
      run: |
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
        git config --global user.name github-actions[bot]
        git clone https://github.com/zed-industries/zed -b main zed

    - name: Build Executable
      run: |
        cd zed
        git checkout tags/v0.167.2
        cargo build --release
        if (Test-Path "C:\cargo_target\release\zed.exe") {
          Write-Host "Build succeeded and zed.exe exists."
        } else {
          Write-Host "Build failed or zed.exe does not exist."
          exit 1
        }
      env:
        CARGO_HOME: C:\cargo
        CARGO_TARGET_DIR: C:\cargo_target
      shell: pwsh

    - name: List Build Output
      run: |
        cd C:\cargo_target\release
        dir
      shell: pwsh

    - name: Compile Setup Wizard
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: zed_wizard.iss
        options: /O+

    - name: Upload Setup Wizard
      uses: actions/upload-artifact@v4
      with:
        name: setup
        path: Output\zed_setup.exe

  Upload:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Download Release Folder
        uses: actions/download-artifact@v4
        with:
          name: setup
          path: Output

      - name: Setup Git Environment
        run: |
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]

      - name: Upload to Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v0.167.2 Zed Windows
          tag_name: v0.167.2
          files: Output/zed_setup.exe
