name: Build Zed for Windows

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Enable Long Paths
      run: |
        reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f
        timeout /t 5

    - name: Set Cargo Home and Target Directory
      run: |
        setx CARGO_HOME C:\cargo
        setx CARGO_TARGET_DIR C:\cargo_target
      shell: cmd

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Install Toolchain
      run: rustup target add wasm32-wasi

    - name: Clone Source Code
      run: |
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
        git config --global user.name github-actions[bot]
        git clone https://github.com/zed-industries/zed -b main zed

    - name: Build Executable
      run: |
        cd zed
        git checkout tags/v0.159.5
        cargo build --release

    - name: Compile Setup Wizard
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: zed_wizard.iss
        options: /O+

    - name: Upload Setup Wizard
      uses: actions/upload-artifact@v4
      with:
        name: setup
        path: Output\zed_setup.exe

  Upload:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Download Release Folder
        uses: actions/download-artifact@v4
        with:
          name: setup
          path: Output

      - name: Setup Git Environment
        run: |
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]

      - name: Upload to Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v0.159.5 Zed Windows
          tag_name: v0.159.5
          files: Output/zed_setup.exe
