name: Build Zed for Windows

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest

    outputs:
      TAG: ${{ steps.set_tag.outputs.TAG }}

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Install Toolchain
      run: rustup target add wasm32-wasi

    - name: Clone Source Code
      run: |
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
        git config --global user.name github-actions[bot]
        git clone https://github.com/zed-industries/zed -b main zed

    - name: Build Executable
      id: set_tag
      run: |
        cd zed
        git fetch --tags
        $tag = git describe --tags (git rev-list --tags --max-count=1)
        echo "TAG=$tag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "::set-output name=TAG::$tag"
        git checkout $tag
        cargo build --release

    - name: Compile Setup Wizard
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: zed_wizard.iss
        options: /O+

    - name: Upload Setup Wizard
      uses: actions/upload-artifact@v4
      with:
        name: setup
        path: Output\zed_setup.exe

  Upload:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Download Release Folder
        uses: actions/download-artifact@v4
        with:
          name: setup
          path: Output

      - name: Setup Git Environment
        run: |
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]

      - name: Upload to Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ needs.Build.outputs.TAG }} Zed Windows
          tag_name: ${{ needs.Build.outputs.TAG }}
          files: Output/zed_setup.exe
